name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: install math library
      run: sudo apt-get install -y libmath-libm-perl
  
    - name: make Activity 1
      run:  make -C ACTIVITY 1-A
      
    - name: make Activity 2
      run:  make -C ACTIVITY 1-B
    
    - name: make Activity 3
      run:  make -C ACTIVITY 2
  
    - name: make Activity 4
      run:  make -C ACTIVITY 3
